- name: Check for iptables
  shell: command -v iptables
  register: iptables
  check_mode: no
  changed_when: false  # Never report as changed
  failed_when: false
  tags:
    - firewall

- name: Fail on no firewall detected
  fail:
    msg: "No firewall detected, install one before proceeding (iptables)"
  when: iptables.rc != 0

- name: Add rules (iptables)
  include: iptables.yml
  when: iptables.rc == 0